---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: operator-controller-manager-rolebinding
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: operator-controller-operator-controller-controller-manager
    namespace: openshift-operator-controller
